
-- 🚨 SCRIPT COMPLET : CRÉATION TABLE + PERMISSIONS TABLE 6MN 🚨

-- 1. CRÉATION DE LA TABLE (Si elle n'existe pas)
CREATE TABLE IF NOT EXISTS observations_6mn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    t REAL,        -- Température
    td REAL,       -- Point de rosée
    u INT,         -- Humidité
    ff REAL,       -- Vent
    fxi REAL,      -- Rafales
    dd INT,        -- Direction
    rr_per REAL,   -- Pluie
    pres REAL,     -- Pression
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(station_id, timestamp)
);

-- 2. INDEX (Pour que ça aille vite)
CREATE INDEX IF NOT EXISTS idx_obs_6mn_station_time ON observations_6mn (station_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_obs_6mn_timestamp ON observations_6mn (timestamp DESC);

-- 3. ACTIVATION SÉCURITÉ
ALTER TABLE observations_6mn ENABLE ROW LEVEL SECURITY;

-- 4. NETTOYAGE ANCIENNES RÈGLES (Pour éviter les erreurs)
DROP POLICY IF EXISTS "Lecture publique" ON observations_6mn;
DROP POLICY IF EXISTS "Ecriture système seulement" ON observations_6mn;
DROP POLICY IF EXISTS "Ecriture publique" ON observations_6mn;
DROP POLICY IF EXISTS "Mise à jour publique" ON observations_6mn;

-- 5. NOUVELLES RÈGLES (Autoriser le site web)
-- Tout le monde peut lire
CREATE POLICY "Lecture publique" ON observations_6mn FOR SELECT USING (true);

-- Tout le monde peut écrire (Site Web)
CREATE POLICY "Ecriture publique" ON observations_6mn FOR INSERT WITH CHECK (true);

-- Tout le monde peut mettre à jour (Anti-Doublon)
CREATE POLICY "Mise à jour publique" ON observations_6mn FOR UPDATE USING (true);

-- Vérification immédiate
SELECT 'La table a été créée avec succès !' as status;
