-- 1. Création de la table pour stocker les relevés 6 minutes (très volumineux)
CREATE TABLE IF NOT EXISTS observations_6mn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID unique ligne
    station_id TEXT NOT NULL,                               -- ID de la station (ex: 59183001)
    timestamp TIMESTAMPTZ NOT NULL,                         -- Date et heure précise du relevé
    
    -- Données Météo
    t REAL,        -- Température (°C)
    td REAL,       -- Point de rosée (°C)
    u INT,         -- Humidité (%)
    ff REAL,       -- Vent moyen (km/h)
    fxi REAL,      -- Rafales (km/h)
    dd INT,        -- Direction vent (°)
    rr_per REAL,   -- Précipitations sur la période (mm)
    pres REAL,     -- Pression (hPa)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Contrainte d'unicité : Pas deux relevés pour la même station à la même heure
    UNIQUE(station_id, timestamp)
);

-- 2. Index pour accélérer les recherches (indispensable quand on aura des millions de lignes)
CREATE INDEX IF NOT EXISTS idx_obs_6mn_station_time ON observations_6mn (station_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_obs_6mn_timestamp ON observations_6mn (timestamp DESC);

-- 3. Politique de sécurité (Lecture publique pour le site, Ecriture protégée)
ALTER TABLE observations_6mn ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lecture publique" ON observations_6mn
    FOR SELECT USING (true);

CREATE POLICY "Ecriture système seulement" ON observations_6mn
    FOR INSERT WITH CHECK (auth.role() = 'service_role');
