-- 1. Création de la table pour stocker les relevés HORAIRES (Standard)
CREATE TABLE IF NOT EXISTS observations_horaire (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    
    -- Données Météo
    t REAL,        -- Température (°C)
    td REAL,       -- Point de rosée (°C)
    u INT,         -- Humidité (%)
    ff REAL,       -- Vent moyen (km/h)
    fxi REAL,      -- Rafales (km/h)
    dd INT,        -- Direction vent (°)
    rr1 REAL,      -- Précipitations sur 1h (mm) - Notez 'rr1' au lieu de 'rr_per'
    pres REAL,     -- Pression (hPa)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    UNIQUE(station_id, timestamp)
);

-- 2. Index
CREATE INDEX IF NOT EXISTS idx_obs_hr_station_time ON observations_horaire (station_id, timestamp DESC);

-- 3. Sécurité
ALTER TABLE observations_horaire ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lecture publique" ON observations_horaire FOR SELECT USING (true);
CREATE POLICY "Ecriture système" ON observations_horaire FOR INSERT WITH CHECK (auth.role() = 'service_role');
